---
- name: Install requirements for Ansible certificate modules
  package:
    name: "{{ _packages[ansible_os_family] }}"
    state: present
  vars:
    _packages:  # see docs of 'community.crypto.x509_certificate' module
      Debian:
        - python3-cryptography
