---
packages:
  from_repo:
    - 'adduser'
    - 'apt-transport-https'
    - 'auditd'
    - 'bash-completion'
    - 'ca-certificates'
    - 'curl'
    - 'ebtables'

    # for opensearch role
    - 'opensearch=2.8.0*'
    - 'opensearch-dashboards=2.8.0*'
    # for curator-opensearch
    - 'python3-venv'
    # for python3-venv
    - 'python3.8-venv'
    # for python3.8-venv
    - 'python3.8'
    # for python3.8
    - 'python3.8-minimal'
    # for python3.8-minimal
    - 'libpython3.8-minimal'

    - 'ethtool'
    - 'filebeat=7.12.1*'
    - 'firewalld'
    - 'fping'
    - 'gnupg2'
    - 'htop'
    - 'iftop'
    - 'jq'

    # for dpkg-scanpackages
    - 'libdpkg-perl'
    - 'libfontconfig1'
    - 'logrotate'
    - 'netcat'
    - 'net-tools'
    - 'nfs-common'

    # for nfs-common
    - 'libtirpc3'
    - 'openjdk-8-jre-headless'
    - 'openssl'
    - 'python3-psycopg2'
    - 'python3-selinux'
    - 'smbclient'
    - 'samba-common'
    - 'software-properties-common'
    - 'sshpass'
    - 'sysstat'

    # for sysstat
    - 'libsensors5'
    - 'tar'
    - 'telnet'
    - 'tmux'
    - 'unzip'
    - 'vim'

    # to make remote-to-remote "synchronize" work in ansible
    - 'rsync'

    # for curl, issue #869
    - 'libcurl4'

    # for openjdk-8-jre-headless
    - 'libnss3'
    - 'libcups2'
    - 'libavahi-client3'
    - 'libavahi-common3'
    - 'libjpeg8'
    - 'libxtst6'
    - 'fontconfig-config'

    # for air-gap repo installation
    - 'apache2'
    - 'apache2-bin'
    - 'apache2-utils'

    # for jq
    - 'libjq1'

    # for gnupg2
    - 'gnupg'
    - 'gpg'
    - 'gpg-agent'
    - 'samba-libs'
    - 'libsmbclient'

    # for firewalld
    - 'ipset'
    - 'python3-decorator'
    - 'python3-slip'
    - 'python3-slip-dbus'

    # for Ansible (certificate modules)
    - 'python3-cryptography'

    # for python3-cryptography
    - 'python3-cffi-backend'

  from_url:
    # Grafana package is not downloaded from repository since it was not reliable (issue #2449)
    'https://dl.grafana.com/oss/release/grafana_8.3.2_amd64.deb':
      sha256: 3f5ecf5726223314aa3147a24c732cc9ccede86b7d703d4835a6fc69d0fffff8
