---
- name: Restore repositories to initial state
  block:
    - name: Re-enable system repositories
      shell: /var/tmp/epi-repository-setup-scripts/enable-system-repos.sh
    - name: Disable epirepo
      shell: /var/tmp/epi-repository-setup-scripts/disable-epirepo-client.sh

- name: Remove epirepo packages directory
  file:
    state: absent
    path: "{{ apache_epirepo_path }}/packages"
  when:
    - specification.teardown.remove.packages is defined
    - specification.teardown.remove.packages

- name: Remove files directory from epirepo
  file:
    state: absent
    path: "{{ apache_epirepo_path }}/files"
  when:
    - specification.teardown.remove.files is defined
    - specification.teardown.remove.files

- name: Disable epirepo and clean up firewall rule
  block:
    - name: Disable epirepo server
      shell: /var/tmp/epi-repository-setup-scripts/disable-repository-server.sh

    - name: Clean up temporary firewall rule for HTTP server
      include_tasks: firewall/clean-up-rule.yml
  when:
    - not custom_repository_url
    - specification.teardown.disable_http_server

- name: Clean up temporary files
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /var/tmp/epi-download-requirements
    - /var/tmp/epi-repository-setup-scripts
    - /var/tmp/enabled-system-repos.txt
    - /var/tmp/enabled-system-repos.tar
