---
# This file is meant to be also used by upgrade role
curator:
  version: '0.0.9'
  venv_dir: /root/venv/curator-opensearch
  config_file_path: /root/.curator/curator.yml
certificates:
  dirs:
    certs: /etc/opensearch
    ca_key: /etc/opensearch
    csr: /etc/opensearch
  dn_attributes_order: ['CN', 'OU', 'O', 'L', 'S', 'C', 'DC']
  files:
    demo:
      root_ca:
        cert: root-ca.pem
      admin:
        cert: kirk.pem
        key: kirk-key.pem
      node:
        cert: esnode.pem
        key: esnode-key.pem
      opensearch_security:
        allow_unsafe_democertificates: false  # if 'false' all demo files must be removed to start OpenSearch
    common:
      subject: &common-subject
        O: Epiphany
        OU: R&D
    root_ca:
      cert:
        filename: epiphany-root-ca.pem
        selfsigned_not_after: 20330712235959Z  # relative time, such as '+3650d', is NOT idempotent
        subject:
          <<: *common-subject
          CN: Epiphany Managed ODFE Root CA
      key:
        filename: epiphany-root-ca-key.pem
    admin:
      cert:
        filename: epiphany-admin.pem
        ownca_not_after: 20330712235959Z  # relative time, such as '+3650d', is NOT idempotent.
        subject:
          <<: *common-subject
          CN: Epiphany Admin
      key:
        filename: epiphany-admin-key.pem
    node:
      cert:
        filename: epiphany-node-{{ ansible_nodename }}.pem
        ownca_not_after: 20330712235959Z  # relative time, such as '+3650d', is NOT idempotent
        subject:
          <<: *common-subject
          CN: "{{ ansible_nodename }}"
      key:
        filename: epiphany-node-{{ ansible_nodename }}-key.pem
ports:
  http: 9200
  transport: 9300
