---
- name: Repository checks
  include_tasks: roles/repository/tasks/preflight/upgrade.yml
  when:
    - groups.repository is defined
    - groups.repository | length == 1
    - "'repository' in group_names"

- name: Node Exporter in K8s checks
  include_tasks: roles/node_exporter/tasks/preflight/upgrade.yml
  when:
    - "'node_exporter' in upgrade_components or upgrade_components|length == 0"
    - k8s_as_cloud_service is defined and k8s_as_cloud_service
    - "'node_exporter' in group_names"
    - "'kubernetes_master' in group_names"
