---
# Kafka tasks - reside on masters

- name: Check if jmx exporter is available
  stat:
    get_attributes: false
    get_checksum: false
    get_mime: false
    path: "{{ prometheus_jmx_exporter_path }}"
  register: exporter

- include_tasks: setup-kafka.yml

- include_tasks: metrics.yml
  when: exporter.stat.exists

- include_tasks: common/start.yml
