---
# Ansible playbook for disabling/enabling repositories before/after Epiphany installation

- hosts: all
  become: true
  become_method: sudo
  become_flags: --login
  tasks:
    - import_role:
        name: repository
        tasks_from: setup
