---
local_repository_url: "http://{{ hostvars[groups.repository[0]].ansible_default_ipv4.address }}/epirepo"
repository_url: "{{ custom_repository_url | default(local_repository_url, true) }}"

kubeconfig:
  local: "{{ inventory_dir }}/kubeconfig"
  remote: /etc/kubernetes/admin.conf

# https://github.com/ansible/ansible/issues/57189
yum_lock_timeout: 300
