---
supported_oses:
  - name: Ubuntu
    version:
      min: '20.04'
      max: '20.04'

# The list of unsupported K8s applications per architecture
unsupported_apps:
  x86_64: []

unsupported_roles:
  - distro: Ubuntu
    arch: x86_64
    roles: []  # all supported
