---
kind: epiphany-cluster
title: Epiphany cluster Config
provider: azure
name: default
specification:
  name: SET_BY_AUTOMATION
  admin_user:
    name: <INPUT_ADMIN_USER>
    key_path: /home/epiuser/.ssh/id_rsa
  cloud:
    subscription_name: <INPUT_SUBSCRIPTION_NAME>
    azure_login:
      tenant_id: <INPUT_TENANT_ID>
  components:
    kafka:
      count: 3
    logging:
      count: 3
    monitoring:
      count: 1
    repository:
      count: 0 # by default the 'repository' role is mapped to the 'monitoring' component to reduce costs
