---
repositories:
  elasticsearch-7:
    id: elasticsearch-7.x
    data: |
      name=Elasticsearch repository for 7.x packages
      baseurl=https://artifacts.elastic.co/packages/oss-7.x/yum
      gpgcheck=1
      enabled=1
      autorefresh=1
      type=rpm-md
    gpg_keys:
      - https://artifacts.elastic.co/GPG-KEY-elasticsearch
