---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: default
specification:
  name: SET_BY_AUTOMATION
  cluster_name: SET_BY_AUTOMATION
  component_key: SET_BY_AUTOMATION
  image_id: SET_BY_AUTOMATION
  key_name: SET_BY_AUTOMATION
  subnet_name: SET_BY_AUTOMATION
  associate_public_ip: SET_BY_AUTOMATION
  use_network_security_groups: SET_BY_AUTOMATION
  availability_zone: SET_BY_AUTOMATION
  security_groups: [] # SET_BY_AUTOMATION
  authorized_to_efs: false
  mount_efs: false
  size: t2.micro
  os_full_name: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20221010
  os_type: linux
  ebs_optimized: false
  disks:
    root: # Updating this section on existing machine will cause resource replacement
      volume_type: gp2
      volume_size: 30
      delete_on_termination: true
      encrypted: true
    additional_disks: []
#      - device_name: "/dev/sdb"
#        volume_type: gp2
#        volume_size: 60
#        delete_on_termination: true
#        encrypted: true
  security:
    rules:
     - name: ssh
       description: Allow SSH
       direction: Inbound
       protocol: Tcp
       destination_port_range: "22"
       source_address_prefix: "0.0.0.0/0"
       destination_address_prefix: "0.0.0.0/0"
     - name: node_exporter
       description: Allow node_exporter traffic
       direction: Inbound
       protocol: Tcp
       destination_port_range: "9100"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: out
       description: Allow out
       direction: Egress
       protocol: "all"
       destination_port_range: "0"
       source_address_prefix: "0.0.0.0/0"
       destination_address_prefix: "0.0.0.0/0"
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: kafka-machine
specification:
  size: t3.medium
  security:
    rules:
     - _merge: true
     - name: kafka_exporter
       description: Allow kafka exporter traffic
       direction: Inbound
       protocol: Tcp
       destination_port_range: "9308"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: zookeeper1
       description: Allow Zookeeper 1
       direction: Inbound
       protocol: "Tcp"
       destination_port_range: "3888"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: zookeeper2
       description: Allow Zookeeper 2
       direction: Inbound
       protocol: "Tcp"
       destination_port_range: "2888"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: zookeeper_client
       description: Allow Zookeeper Client
       direction: Inbound
       protocol: "Tcp"
       destination_port_range: "2181"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: kafka_client_9092
       description: Allow Kafka Client
       direction: Inbound
       protocol: "Tcp"
       destination_port_range: "9092"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: kafka_ssl_client_9093
       description: Allow Kafka SSL Client
       direction: Inbound
       protocol: "Tcp"
       destination_port_range: "9093"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: monitoring-traffic
       description: Allow monitoring subnet traffic
       direction: Inbound
       protocol: ALL
       destination_port_range: "0"
       source_address_prefix: "10.1.4.0/24"
       destination_address_prefix: "0.0.0.0/0"
     - name: kubernetes-traffic
       description: Allow Kubernetes subnet traffic
       direction: Inbound
       protocol: ALL
       destination_port_range: "0"
       source_address_prefix: "10.1.1.0/24"
       destination_address_prefix: "0.0.0.0/0"
     - name: kubernetes-traffic2
       description: Allow Kubernetes subnet traffic
       direction: Inbound
       protocol: ALL
       destination_port_range: "0"
       source_address_prefix: "10.1.2.0/24"
       destination_address_prefix: "0.0.0.0/0"
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: monitoring-machine
specification:
  size: t3.medium
  security:
    rules:
     - _merge: true
     - name: prometheus
       description: Allow connection to Prometheus
       direction: Inbound
       protocol: Tcp
       destination_port_range: "9090"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: grafana
       description: Allow connection to Grafana
       direction: Inbound
       protocol: Tcp
       destination_port_range: "3000"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: logging-machine
specification:
  size: t3.large
  security:
    rules:
     - _merge: true
     - name: Elastic
       description: Allow Elastic
       direction: Inbound
       protocol: "Tcp"
       destination_port_range: "9200"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: Elastic2
       description: Allow Elastic
       direction: Inbound
       protocol: "Tcp"
       destination_port_range: "9300"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: OpenSearchDashboards
       description: Allow OpenSearch Dashboards
       direction: Inbound
       protocol: "Tcp"
       destination_port_range: "5601"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: single-machine
specification:
  size: t3.xlarge
  authorized_to_efs: true
  mount_efs: true
  security:
    rules:
     - _merge: true
     - name: repository
       description: Allow repository traffic
       direction: Inbound
       protocol: Tcp
       destination_port_range: "80"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: subnet-traffic
       description: Allow subnet traffic
       direction: Inbound
       protocol: ALL
       destination_port_range: "0"
       source_address_prefix: "10.1.1.0/24"
       destination_address_prefix: "0.0.0.0/0"
---
kind: infrastructure/virtual-machine
title: "Virtual Machine Infra"
provider: aws
name: repository-machine
specification:
  disks:
    root:
      volume_size: 64
  size: t2.medium
  security:
    rules:
     - _merge: true
     - name: repository
       description: Allow repository traffic
       direction: Inbound
       protocol: Tcp
       destination_port_range: "80"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
     - name: image_registry
       description: Allow image registry traffic
       direction: Inbound
       protocol: Tcp
       destination_port_range: "5000"
       source_address_prefix: "10.1.0.0/20"
       destination_address_prefix: "0.0.0.0/0"
