---
- name: Copy kubeconfig to Prometheus host
  copy:
    src: "{{ kubeconfig.local }}"
    dest: "{{ specification.config_directory }}/kubeconfig"
    owner: prometheus
    group: prometheus
    mode: u=r,go=

- name: Load kubeconfig
  include_vars:
    file: "{{ kubeconfig.local }}"
    name: kubeconfig_content
  no_log: True

- name: Create K8s token file
  copy:
    content: "{{ kubeconfig_content.users[0].user.token }}"
    dest: "{{ specification.config_directory }}/k8s-token"
    owner: prometheus
    group: prometheus
    mode: u=r,go=
  no_log: True

- name: Clear kubeconfig content in memory
  set_fact:
    kubeconfig_content: null

- name: Apply rolebinding to K8s for Prometheus
  become: false
  command: "kubectl apply -f {{ role_path }}/files/k8s-rolebinding.yml"
  run_once: true
  delegate_to: localhost
