---
- name: Check if Alertmanager is enabled
  set_fact:
    is_alertmanager_enabled: "{{ specification.alertmanager.enable }}"

- name: Include Blackbox exporter configuration
  include_vars:
    file: roles/blackbox_exporter/vars/main.yml
    name: blackbox_exporter_vars

- name: Configure prometheus
  template:
    src: "prometheus.yml.j2"
    dest: "{{ specification.config_directory }}/prometheus.yml"
    force: true
    owner: prometheus
    group: prometheus
    mode: u=rw,g=r,o=
    validate: "/usr/local/bin/promtool check config %s"
    backup: true
  notify:
    - Restart Prometheus

- name: Copy Prometheus custom static targets
  copy:
    src: "{{ item }}"
    dest: "{{ specification.config_directory }}/file_sd/{{ item | splitext | difference(['.yml']) | join('') }}.yml"
    force: true
    owner: prometheus
    group: prometheus
    mode: u=rw,g=r,o=
  with_fileglob:
    - prometheus/targets/*
