---
- name: Apply rolebinding to K8s for Prometheus
  become: false
  command: "kubectl apply -f {{ role_path }}/files/k8s-rolebinding.yml"
  run_once: true
  delegate_to: localhost

- name: Copy kubeconfig to Prometheus host
  copy:
    src: "{{ kubeconfig.local }}"
    dest: "{{ specification.config_directory }}/kubeconfig"
    owner: prometheus
    group: prometheus
    mode: u=r,go=

- name: Get Kubernetes bearer token for Prometheus
  become: false
  shell: |-
    kubectl get $(kubectl get secrets -n kube-system -o name | grep prometheus) \
      -n kube-system \
      -o jsonpath='{.data.token}'
  register: kube_token
  delegate_to: localhost
  run_once: true

- name: Create K8s token file
  copy:
    content: "{{ kube_token.stdout | b64decode }}"
    dest: "{{ specification.config_directory }}/k8s-token"
    owner: prometheus
    group: prometheus
    mode: u=r,go=
  no_log: true

- name: Clear kube_token in memory
  set_fact:
    kube_token: null
