---
- name: Keycloak checks
  run_once: true
  delegate_to: localhost
  module_defaults:
    assert:
      quiet: true
  block:
    - name: Include vars from keycloak role
      include_vars:
        file: roles/keycloak/vars/main.yml
        name: keycloak_vars
